//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertex.Resources.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin construction of output XML document.
        /// </summary>
        internal static string BeginConstructXMLInfo {
            get {
                return ResourceManager.GetString("BeginConstructXMLInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automata status reseted successfully..
        /// </summary>
        internal static string CCAResetedInfo {
            get {
                return ResourceManager.GetString("CCAResetedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing Cells data....
        /// </summary>
        internal static string CellsSyncInfo {
            get {
                return ResourceManager.GetString("CellsSyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cells updated..
        /// </summary>
        internal static string CellsUpdatedInfo {
            get {
                return ResourceManager.GetString("CellsUpdatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentRanking= .
        /// </summary>
        internal static string CurrentRankingHint {
            get {
                return ResourceManager.GetString("CurrentRankingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful CurRule= .
        /// </summary>
        internal static string CurRulUnsuccessfulHint {
            get {
                return ResourceManager.GetString("CurRulUnsuccessfulHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossOverPoint is .
        /// </summary>
        internal static string CVPHint {
            get {
                return ResourceManager.GetString("CVPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag&amp;Drop the source file here, and then hit enter. You can also enter the file&apos;s location manually..
        /// </summary>
        internal static string DragAndDropInfo {
            get {
                return ResourceManager.GetString("DragAndDropInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error happened when initializing DynamicViewer: .
        /// </summary>
        internal static string DynamicViewerErrorHint {
            get {
                return ResourceManager.GetString("DynamicViewerErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully initialized DynamicViewer at .
        /// </summary>
        internal static string DynamicViewerSuccessHint {
            get {
                return ResourceManager.GetString("DynamicViewerSuccessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML construction done..
        /// </summary>
        internal static string EndXMLConstructionInfo {
            get {
                return ResourceManager.GetString("EndXMLConstructionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter main loop....
        /// </summary>
        internal static string EnterMainLoopHint {
            get {
                return ResourceManager.GetString("EnterMainLoopHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment profile: .
        /// </summary>
        internal static string EnvFileHint {
            get {
                return ResourceManager.GetString("EnvFileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment file parsing done successfully..
        /// </summary>
        internal static string EnvFileParsingDoneInfo {
            get {
                return ResourceManager.GetString("EnvFileParsingDoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Syntax error. Details: .
        /// </summary>
        internal static string EnvSyntaxError {
            get {
                return ResourceManager.GetString("EnvSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating rule: .
        /// </summary>
        internal static string EvaluatingHint {
            get {
                return ResourceManager.GetString("EvaluatingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute[.
        /// </summary>
        internal static string ExecutionHint {
            get {
                return ResourceManager.GetString("ExecutionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER key to close this window..
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open export file to save resulted rule: .
        /// </summary>
        internal static string ExportRuleErrorHint {
            get {
                return ResourceManager.GetString("ExportRuleErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting resulted rule to file: .
        /// </summary>
        internal static string ExportRuleHint {
            get {
                return ResourceManager.GetString("ExportRuleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported resulted rule to file successfully..
        /// </summary>
        internal static string ExportRuleSuccessInfo {
            get {
                return ResourceManager.GetString("ExportRuleSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User should complete this configuration.
        /// </summary>
        internal static string ExportRuleXMLCommentContent {
            get {
                return ResourceManager.GetString("ExportRuleXMLCommentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting SVG file to: .
        /// </summary>
        internal static string ExportSVGHint {
            get {
                return ResourceManager.GetString("ExportSVGHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting SVG Snapshot to .
        /// </summary>
        internal static string ExportSVGSnapshotHead {
            get {
                return ResourceManager.GetString("ExportSVGSnapshotHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVG file exported successfully..
        /// </summary>
        internal static string ExportSVGSuccessInfo {
            get {
                return ResourceManager.GetString("ExportSVGSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has successfully generated the executable rule..
        /// </summary>
        internal static string FinalSuccessInfo {
            get {
                return ResourceManager.GetString("FinalSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating G0 done..
        /// </summary>
        internal static string G0OKInfo {
            get {
                return ResourceManager.GetString("G0OKInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating G1 done..
        /// </summary>
        internal static string G1OKInfo {
            get {
                return ResourceManager.GetString("G1OKInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version doesn&apos;t support networking. This line of configuration is ignored..
        /// </summary>
        internal static string NoNetworkingFeatureWarn {
            get {
                return ResourceManager.GetString("NoNetworkingFeatureWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some feature is not implemented now. Details:.
        /// </summary>
        internal static string NotImplementedHint {
            get {
                return ResourceManager.GetString("NotImplementedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is not supported now. Details: .
        /// </summary>
        internal static string NotSupportedError {
            get {
                return ResourceManager.GetString("NotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;--feature&apos; parameter specified for program..
        /// </summary>
        internal static string NoValidParamError {
            get {
                return ResourceManager.GetString("NoValidParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producing new rule from history..
        /// </summary>
        internal static string ProduceRuleInfo {
            get {
                return ResourceManager.GetString("ProduceRuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 .
        /// </summary>
        internal static string RankingDecHint {
            get {
                return ResourceManager.GetString("RankingDecHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 .
        /// </summary>
        internal static string RankingIncHint {
            get {
                return ResourceManager.GetString("RankingIncHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For help information. use &apos;vertex.exe --help&apos; instead..
        /// </summary>
        internal static string ReferToHelpIndication {
            get {
                return ResourceManager.GetString("ReferToHelpIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultedRule= .
        /// </summary>
        internal static string ResultedRuleHint {
            get {
                return ResourceManager.GetString("ResultedRuleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving XML output to: .
        /// </summary>
        internal static string RuleXMLSaveHint {
            get {
                return ResourceManager.GetString("RuleXMLSaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Evolve feature....
        /// </summary>
        internal static string StartEvolveVerbose {
            get {
                return ResourceManager.GetString("StartEvolveVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting SVG export function..
        /// </summary>
        internal static string StartSVGExportInfo {
            get {
                return ResourceManager.GetString("StartSVGExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVGSnapshot file exported successfully..
        /// </summary>
        internal static string SVGExportSuccessInfo {
            get {
                return ResourceManager.GetString("SVGExportSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks construction OK..
        /// </summary>
        internal static string TasksConstructedInfo {
            get {
                return ResourceManager.GetString("TasksConstructedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tasks OK..
        /// </summary>
        internal static string TasksDoneInfo {
            get {
                return ResourceManager.GetString("TasksDoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success = false for Index = .
        /// </summary>
        internal static string TestFailureHint {
            get {
                return ResourceManager.GetString("TestFailureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success = true for Index = .
        /// </summary>
        internal static string TestSuccessHint {
            get {
                return ResourceManager.GetString("TestSuccessHint", resourceCulture);
            }
        }
    }
}
