//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertex.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vertex.Resources.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始构建XML文档..
        /// </summary>
        internal static string BeginConstructXMLInfo {
            get {
                return ResourceManager.GetString("BeginConstructXMLInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动机状态重置成功.
        /// </summary>
        internal static string CCAResetedInfo {
            get {
                return ResourceManager.GetString("CCAResetedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在同步元胞状态.
        /// </summary>
        internal static string CellsSyncInfo {
            get {
                return ResourceManager.GetString("CellsSyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有元胞状态已更新.
        /// </summary>
        internal static string CellsUpdatedInfo {
            get {
                return ResourceManager.GetString("CellsUpdatedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前的分数是.
        /// </summary>
        internal static string CurrentRankingHint {
            get {
                return ResourceManager.GetString("CurrentRankingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杂交点是.
        /// </summary>
        internal static string CVPHint {
            get {
                return ResourceManager.GetString("CVPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicViewer 创建失败.
        /// </summary>
        internal static string DynamicViewerErrorHint {
            get {
                return ResourceManager.GetString("DynamicViewerErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功地在此处初始化了动态SVG查看器:.
        /// </summary>
        internal static string DynamicViewerSuccessHint {
            get {
                return ResourceManager.GetString("DynamicViewerSuccessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML 构建完成..
        /// </summary>
        internal static string EndXMLConstructionInfo {
            get {
                return ResourceManager.GetString("EndXMLConstructionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进入主循环.
        /// </summary>
        internal static string EnterMainLoopHint {
            get {
                return ResourceManager.GetString("EnterMainLoopHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 环境配置文件:.
        /// </summary>
        internal static string EnvFileHint {
            get {
                return ResourceManager.GetString("EnvFileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 环境文件解析成功.
        /// </summary>
        internal static string EnvFileParsingDoneInfo {
            get {
                return ResourceManager.GetString("EnvFileParsingDoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML 语法错误, 细节:.
        /// </summary>
        internal static string EnvSyntaxError {
            get {
                return ResourceManager.GetString("EnvSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在评估规则.
        /// </summary>
        internal static string EvaluatingHint {
            get {
                return ResourceManager.GetString("EvaluatingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行[.
        /// </summary>
        internal static string ExecutionHint {
            get {
                return ResourceManager.GetString("ExecutionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按回车键来关闭此窗口.
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 规则文件导出失败.
        /// </summary>
        internal static string ExportRuleErrorHint {
            get {
                return ResourceManager.GetString("ExportRuleErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出规则文件至.
        /// </summary>
        internal static string ExportRuleHint {
            get {
                return ResourceManager.GetString("ExportRuleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已成功导出规则文件.
        /// </summary>
        internal static string ExportRuleSuccessInfo {
            get {
                return ResourceManager.GetString("ExportRuleSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户应补全此设置..
        /// </summary>
        internal static string ExportRuleXMLCommentContent {
            get {
                return ResourceManager.GetString("ExportRuleXMLCommentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出SVG至.
        /// </summary>
        internal static string ExportSVGHint {
            get {
                return ResourceManager.GetString("ExportSVGHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在导出目前的SVG至.
        /// </summary>
        internal static string ExportSVGSnapshotHead {
            get {
                return ResourceManager.GetString("ExportSVGSnapshotHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVG文件导出成功.
        /// </summary>
        internal static string ExportSVGSuccessInfo {
            get {
                return ResourceManager.GetString("ExportSVGSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正确的可执行规则已生成.
        /// </summary>
        internal static string FinalSuccessInfo {
            get {
                return ResourceManager.GetString("FinalSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G0生成成功.
        /// </summary>
        internal static string G0OKInfo {
            get {
                return ResourceManager.GetString("G0OKInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G1生成成功.
        /// </summary>
        internal static string G1OKInfo {
            get {
                return ResourceManager.GetString("G1OKInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此版本不支持网络, 这行配置无效.
        /// </summary>
        internal static string NoNetworkingFeatureWarn {
            get {
                return ResourceManager.GetString("NoNetworkingFeatureWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有些东西不被支持. 细节:.
        /// </summary>
        internal static string NotSupportedError {
            get {
                return ResourceManager.GetString("NotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从历史生成新规则.
        /// </summary>
        internal static string ProduceRuleInfo {
            get {
                return ResourceManager.GetString("ProduceRuleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1 .
        /// </summary>
        internal static string RankingDecHint {
            get {
                return ResourceManager.GetString("RankingDecHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 .
        /// </summary>
        internal static string RankingIncHint {
            get {
                return ResourceManager.GetString("RankingIncHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 得到的规则是.
        /// </summary>
        internal static string ResultedRuleHint {
            get {
                return ResourceManager.GetString("ResultedRuleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在保存XML输出至.
        /// </summary>
        internal static string RuleXMLSaveHint {
            get {
                return ResourceManager.GetString("RuleXMLSaveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始SVG导出.
        /// </summary>
        internal static string StartSVGExportInfo {
            get {
                return ResourceManager.GetString("StartSVGExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVG快照导出成功.
        /// </summary>
        internal static string SVGExportSuccessInfo {
            get {
                return ResourceManager.GetString("SVGExportSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有任务创建完成.
        /// </summary>
        internal static string TasksConstructedInfo {
            get {
                return ResourceManager.GetString("TasksConstructedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有任务完成.
        /// </summary>
        internal static string TasksDoneInfo {
            get {
                return ResourceManager.GetString("TasksDoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对于此测试失败.
        /// </summary>
        internal static string TestFailureHint {
            get {
                return ResourceManager.GetString("TestFailureHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对于此测试成功.
        /// </summary>
        internal static string TestSuccessHint {
            get {
                return ResourceManager.GetString("TestSuccessHint", resourceCulture);
            }
        }
    }
}
